---
collections:
  - name: ibm.power_aix
    version: 2.2.1

  - name: lpars.power
    source: https://github.com/LPARS/ansible-collection-power
    type: git

roles:
  - name: bertvv.dhcp
    version: v3.2.0
