---
- name: "Ensure base DHCP is configured on netboot server"
  hosts: netboot
  become: true
  roles:
    - name: bertvv.dhcp

- name: "Create and install logical partitions"
  hosts: hmc
  gather_facts: false
  roles:
    - iambryant.power.lpar
